version: '3'
services:
  redis-server:
    image: 'redis'
  node-app:
    restart: on-failure
    build:
      context: .
      args:
        http_proxy: http://12.239.214.4:8080
    ports:
      - "4001:8081"